spring:
  datasource:
    url: jdbc:postgresql://db:5432/db_task
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

api:
  security:
    token:
      secret: your-secret-key-here

server:
  port: 8080
